### ISSUE TITLE
BWST - CI- und Snapshot-Pipelines gegen Branch new-mono-sans prüfen

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri-theme-bwst#18]
### User Story: Überprüfung und Optimierung der CI-Pipeline für den Branch `new-noto-sans`

**Als** Entwickler,  
**möchte ich** sicherstellen, dass die Änderungen im Branch `new-noto-sans`, die von Conterra erhalten wurden, korrekt in der CI-Pipeline geprüft werden,  
**damit** keine Abweichungen übersehen werden und alle notwendigen Artefakte sowie Snapshot-Updates wie erwartet erzeugt und gepusht werden.

#### Akzeptanzkriterien:
1. Die CI-Pipeline überprüft erfolgreich alle Änderungen im Branch `new-noto-sans`.
2. Die Pipeline zeigt keine Abweichungen im CI-Lauf an, falls alle Tests und Checks erfolgreich sind.
3. Bei einem Abweichungen der Snapshots, soll der CI-Lauf die Abweichungen als Artefakt anbieten.
4. Die Snapshot-Update-Pipeline aktualisiert die Snapshots korrekt und pusht diese bei Bedarf in das Repository.
5. Eine Dokumentation über die Durchführung und die Ergebnisse der Pipeline-Läufe wird bereitgestellt.

#### Technische Details:
- Branch: `new-noto-sans`
- Vorbild: [Pipeline im kolibri-Repository](https://github.com/public-ui/kolibri/blob/develop/.github/workflows/ci.yml)

**Comment by sdvg** [comment]
- Fehlgeschlagener Build, bei dem jetzt die Artefakte heruntergeladen werden können: https://github.com/public-ui/kolibri-theme-bwst/actions/runs/10922936112
- Erfolgreiches Snapshot Update ([Action](https://github.com/public-ui/kolibri-theme-bwst/actions/runs/10923264098), [Commit](https://github.com/public-ui/kolibri-theme-bwst/pull/16/commits/8edb7995e2ae3a90d6b592721c66fcf7a6629a7e))
- Erfolgreicher Build: https://github.com/public-ui/kolibri-theme-bwst/actions/runs/10923327641/job/30319681043
- Dokumentation: https://github.com/public-ui/kolibri-theme-bwst/blob/c3f4406418bdb85b357b7f56c9b7cb217303253d/README.md#snapshot-tests-f%C3%BCr-visuelle-%C3%A4nderungen
